spring.application.name=student-crud-app

spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Make Necessary adjustments for server port if 8080 is in use!
server.port=8080
